# Generated by Django 3.2.25 on 2024-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prioritylevels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioritylevel',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='prioritylevel',
            name='description',
            field=models.TextField(default='placeholder description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prioritylevel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
