# Generated by Django 3.2.25 on 2024-03-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prioritylevels', '0002_auto_20240319_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prioritylevel',
            name='description',
        ),
    ]
