# Generated by Django 3.2.25 on 2024-03-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EDUCATION', 'Education'), ('WORK', 'Work'), ('HEALTH_AND_FITNESS', 'Health & Fitness'), ('HOBBIES', 'Hobbies'), ('SELF_CARE', 'Self Care'), ('HOME', 'Home'), ('SOCIAL', 'Social')], max_length=20)),
            ],
        ),
    ]
