# Generated by Django 3.2.25 on 2024-03-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20240319_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
