# Generated by Django 3.2.25 on 2024-03-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
