# Generated by Django 3.2.25 on 2024-03-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_description'),
        ('prioritylevels', '0003_remove_prioritylevel_description'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='prioritylevels.prioritylevel'),
            preserve_default=False,
        ),
    ]
